version: '3.3'

volumes:
  postgres_data:
    driver: local
  static_value:
  media_value:
  letsencrypt_certs:
  certbot_acme_challenge:

services:
  db:
    image: postgres:14.3-alpine
    env_file:
      - ../bbt_admin/bbt_admin/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  backend:
    build:
      context: ../
      dockerfile: ./infra/backend/Dockerfile
    env_file:
      - ../bbt_admin/bbt_admin/.env
    volumes:
      - ../bbt_admin:/code
      - static_value:/code/static/
      - media_value:/code/media/
    depends_on:
      - db

  nginx:
    image: nginx:1.22-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static_value:/var/html/static/
      - media_value:/var/html/media/
      - ./nginx/config/nginx.conf:/etc/nginx/conf.d/default.conf
      - letsencrypt_certs:/etc/letsencrypt
      - certbot_acme_challenge:/var/www/certbot
    depends_on:
      - backend
    restart: always

  certbot:
    image: certbot/certbot
    volumes:
      - letsencrypt_certs:/etc/letsencrypt
      - certbot_acme_challenge:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  bot:
    build:
      context: ../
      dockerfile: ./infra/bot/Dockerfile
    env_file:
      - ../bbt_admin/bbt_admin/.env
    volumes:
      - ../bot:/app
